### ISSUE TITLE
することができますって冗長じゃないですかね？

### ISSUE THREAD

**Issue by kyonmm** [mackerelio/documents#1]
技術文書では、「することができます」っていうのは「できます」で十分じゃないですかね。。。なにか方針があるならいいんですが。。。

対象ファイルは次です。（blog配下はもう別にいいかなって思いますので）

```
git grep することができます content/ja/docs/entry/*.md
```

```
content/ja/docs/entry/custom-checks.md:- env: commandに渡す環境変数を指定することができます。TOMLの[Table][]もしくは[Inline Table][]で指定します。
content/ja/docs/entry/custom-checks.md:- action.env: action.commandに渡す環境変数を指定することができます。TOMLの[Table][]もしくは[Inline Table][]で指定します。
content/ja/docs/entry/custom-checks.md:- memo: チェック監視に対してメモを設定することができます。ここで指定した文字列は、アラート通知・アラート詳細画面・ホスト詳細ページで確認することができます。
content/ja/docs/entry/custom-checks.md:標準出力には補助的なメッセージを追加することができます。メッセージ長の上限は1024文字までです。
content/ja/docs/entry/expression-monitoring.md:Mackerelでは `linearRegression()`, `timeLeftForecast()`といった線形回帰の関数を利用することができます。
content/ja/docs/entry/glossary.md:ロールはサービスに所属するホストをさらにその「役割」（アプリケーション、データベース、etc…）によって分類する概念です。Mackerelではホストの状況をロールごとにまとめて可視化することができます。
content/ja/docs/entry/glossary.md:mackerel-agent が定期的に収集するホストの状況です。CPU・メモリの利用状況や、IOの量などが計測され、Mackerelのサーバに自動的に送信されます。ウェブ上でこれらの値をグラフィカルに確認することができます。
```

**Comment by daiksy** [comment]
ご指摘ありがとうございます。
こういった表現の統一について、 textlintなどを入れると良いのではないかと議論をしていました。

**Comment by kyonmm** [comment]
lintという意味ではmarkdownとしてエラーになりそうなものが散見されるので、できればなおしておいたほうがメンテはしやすそうとおもいました。

デプロイされているHTMLはくずれていないのでそこまで気にしなくてもいいとおもうんですが。ローカルのビューアとかで確認するときにくずれがちとかそういうのがきになりそう。

たとえば content/ja/docs/entry/external-monitoring.md とかで `##URL外形監視を設定する` みたいに `#` のうしろにスペースがないとか。。。
こういうのもmarkdownlintであるていどはふせげるかなーとか。

**Comment by kyonmm** [comment]
(まちがってクローズおしてしまったのでリオープンしました。。。

**Comment by a-know** [comment]
ご指摘ありがとうございます！チーム内でも確認が取れましたため、修正を実施しました。 https://github.com/mackerelio/documents/pull/2

ご指摘いただいた Markdown としての不備についても、一緒に修正しております。
markdownlintなどの導入についても、引き続き検討をしていきたいと思います。貴重なご意見、ありがとうございます！

**Comment by kyonmm** [comment]
@a-know ありがとうございます。確認できました。いいかんじですね。

**Comment by a-know** [comment]
https://github.com/mackerelio/documents/pull/2 にて対応完了しました。ご指摘ありがとうございました。
